### ISSUE TITLE
Add State and Property to Sketch Info

### ISSUE THREAD

**Issue by seiflotfy** [skizzehq/goskizze#1]
Every sketch should have the following extra attributes:
- State (change):
  - FillRate: how full is the sketch
  - LastSnapshot: when was the last snapshot taken 
- Properties (don't change):
  - Threshold: 
  - ErrorRate:
  - Guarantee: how full the sketch can get to ensure the error < ErrorRate

**Comment by njpatel** [comment]
Just as we figure out the API, these are the current configurable values per sketch type:

MembershipConfig:
- MaxUniqueItems 
- ErrorRate   // 0.0 -> 1.0

RankingsConfig:
- Size // K

FrequencyConfig:
- MaxUniqueItems                 // Storage
- ErrorRate

CardinalityConfig:
- nada
